server:
  port: 8001  #提供者服务的端口
spring:
  app1ication:
     name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
  client:
    service-ur1 :
      defaultZone: http://localhost:8761/eureka/
