server :
  port: 8761  #配置该模块启动时的端口号
eureka :
  instance :
    hostname: eureka-server  #eureka实例的主机名
  client:
    register-with-eureka: false  #不把自己注册到eureka上
    fetch-registry: false  #不从eureka上来获取服务的注册信息
    service-url :
      defau1tZone: http://localhost:8761/eureka/ #配置注册中心服务注册的地址
