spring:
  application:
    name: custum-ticket
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
  client:
    service-ur1 :
      defaultZone: http://localhost:8761/eureka/